### ISSUE TITLE
Export siff for Cytoscape

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/correlation_analysis#2]
@workflow4metabolomics/ms 

This tool is generating some export for Cytoscape in siff format.

In My Humble Opinion, if it's usefull, we must consider to create a separate tool for this task.

What do you think about that?

**Comment by melpetera** [comment]
This export for Cytoscape is tightly linked to the correlation calculation. It is not just about format, it is about what a sif file means. So I am not sure what a dedicated Cytoscape tool would looked like. A tool having a correlation matrix as input and the corresponding sif file as output? What about correlation threshold to keep? Would you take the "Correlation Cytoscape threshold" parameter out from MCA to put it in this tool? 

This could make sense. I am only wondering about how usefull it would be. The sif format IS essential relatively to the MCA module, but this tool is the only one in all our workflows to generate a correlation matrix, so no other tool than this one could be put as input for a dedicated Cytoscape tool in W4M. Or maybe I am missing something? (which is absolutely possible)

**Comment by lecorguille** [comment]
I guess the one who are missing something is me.
I didn't know that it was correlated to the correlation :)
Thanks for your lights
